title: Personal Portfolio
author: Elias
description: Developer Site for Elias
baseurl: github.com/STORMTR00P3R/STORMTR00P3R.github.io
domain: https://github.com/STORMTR00P3R/STORMTR00P3R.github.io
github_username: STORMTR00P3R

plugins:
  - jekyll-feed